name: Aggiorna Fonte Azzurra

on:
  # Esegui ogni 6 ore
  schedule:
    - cron: '0 */6 * * *'
  # Consente l'esecuzione manuale
  workflow_dispatch:

jobs:
  update-main:
    # Permessi necessari per scrivere i file aggiornati nel repository
    permissions:
      contents: write 
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4 

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          # Versione di Python stabile
          python-version: '3.11' 

      - name: Install dependencies
        run: |
          set -e
          python -m pip install --upgrade pip
          pip install feedparser beautifulsoup4 requests

      - name: Esegui aggregator.py
        run: |
          set -e
          python aggregator.py

      - name: Commit e push su main
        run: |
          set -e
          # Configura l'utente Git
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions@github.com"
          
          # Aggiungi i file che lo script dovrebbe aver modificato
          git add index.html feed.json
          
          # Controlla se ci sono modifiche da committare
          if ! git diff --cached --quiet; then
            # Aggiunto [skip ci] per evitare loop infiniti di workflow
            git commit -m 'Aggiornamento automatico articoli [skip ci]'
            
            # Push con GITHUB_TOKEN predefinito (il modo più semplice e sicuro)
            git push
            
            echo "Modifiche committate e pushati."
          else
            echo "Nessuna modifica da committare o pushati."
          fi
